raw_text = """
Q1. What is a Talk-to-Data Agent?

A. Database

B. AI Agent

C. Web Browser

D. Cache

✅ Answer: B

Q2. A Talk-to-Data Agent converts

A. SQL -> HTML

B. Natural Language -> SQL

C. JSON -> XML

D. CSV -> PDF

✅ Answer: B

Q3. Which component receives the user request first?

A. Database

B. API Gateway

C. Redis

D. Kafka

✅ Answer: B

Q4. Which component understands user intent?

A. Redis

B. LLM

C. PostgreSQL

D. Kafka

✅ Answer: B

Q5. Which component creates the execution plan?

A. Planner

B. Database

C. Browser

D. Cache

✅ Answer: A

Q6. SQL is generated by

A. GPU

B. SQL Generator

C. Redis

D. Docker

✅ Answer: B

Q7. SQL executes on

A. Database

B. Kafka

C. RabbitMQ

D. Redis

✅ Answer: A

Q8. Which stores business data?

A. Redis

B. PostgreSQL

C. Cache

D. Browser

✅ Answer: B

Q9. Which stores temporary data?

A. PostgreSQL

B. Redis

C. Oracle

D. MySQL

✅ Answer: B

Q10. Which improves repeated query performance?

A. Kafka

B. Redis Cache

C. Docker

D. CSS

✅ Answer: B

Q11. LLM primarily performs

A. Query Understanding

B. SQL Storage

C. Image Compression

D. API Routing

✅ Answer: A

Q12. Which component selects the tools?

A. Planner

B. Browser

C. SQL

D. HTML

✅ Answer: A

Q13. Memory is mainly used for

A. Previous Conversations

B. SQL Tables

C. CSS

D. APIs

✅ Answer: A

Q14. Which component remembers chat history?

A. Memory

B. GPU

C. Queue

D. Browser

✅ Answer: A

Q15. Which component generates the final answer?

A. Response Generator

B. SQL

C. Database

D. API Gateway

✅ Answer: A

Q16. Which is a structured data source?

A. PostgreSQL

B. Excel

C. MySQL

D. All of the Above

✅ Answer: D

Q17. Which is an unstructured data source?

A. PDF

B. Word Document

C. Text File

D. All of the Above

✅ Answer: D

Q18. Which database is commonly used for vector search?

A. Pinecone

B. PostgreSQL

C. Redis

D. MySQL

✅ Answer: A

Q19. Which database stores embeddings?

A. Vector Database

B. Oracle

C. SQL Server

D. SQLite

✅ Answer: A

Q20. RAG mainly uses

A. Vector Database

B. CSS

C. Docker

D. RabbitMQ

✅ Answer: A

Q21. Which flow is correct?

A. User -> Database

B. User -> API -> Planner -> LLM -> SQL -> Database

C. User -> Redis

D. User -> Kafka

✅ Answer: B

Q22. Which component validates generated SQL?

A. Query Validator

B. Redis

C. Kafka

D. CSS

✅ Answer: A

Q23. Which component executes SQL?

A. Executor

B. Planner

C. LLM

D. Memory

✅ Answer: A

Q24. Which component formats database results?

A. Result Processor

B. Browser

C. API

D. Redis

✅ Answer: A

Q25. Which component converts results into natural language?

A. Response Generator

B. SQL

C. PostgreSQL

D. Kafka

✅ Answer: A

Q26. Which queries should be cached?

A. Frequently Asked Queries

B. Dashboard Results

C. Reports

D. All of the Above

✅ Answer: D

Q27. Why cache generated SQL?

A. Faster Response

B. Lower LLM Cost

C. Reduced Database Load

D. All of the Above

✅ Answer: D

Q28. Which cache technology is commonly used?

A. Redis

B. Oracle

C. Cassandra

D. SQLite

✅ Answer: A

Q29. Which component handles long-running report generation?

A. Kafka / RabbitMQ

B. Redis

C. Browser

D. CSS

✅ Answer: A

Q30. AI Report Generation should be

A. Synchronous

B. Asynchronous

C. Manual

D. Offline

✅ Answer: B

Q31. Which technology processes background jobs?

A. RabbitMQ

B. Redis

C. PostgreSQL

D. React

✅ Answer: A

Q32. Kafka is mainly used for

A. Event Streaming

B. CSS

C. SQL

D. Images

✅ Answer: A

Q33. Why use a Planner Agent?

A. Decide execution steps

B. Store images

C. Compress files

D. Render UI

✅ Answer: A

Q34. Which component calls external APIs?

A. Tool Manager

B. GPU

C. Browser

D. Redis

✅ Answer: A

Q35. AI Agent uses Memory because

A. It remembers previous conversations

B. It stores HTML

C. It replaces SQL

D. It increases GPU speed

✅ Answer: A

Q36. Which technology reduces repeated LLM calls?

A. Redis Cache

B. CSS

C. Bootstrap

D. Docker

✅ Answer: A

Q37. Which architecture is BEST?

A. User -> Database

B. User -> LLM -> Database

C. User -> API -> Planner -> LLM -> SQL -> Database -> Response

D. User -> Redis

✅ Answer: C

Q38. Which component should NOT directly access the database?

A. Browser

B. Repository

C. Executor

D. API Backend

✅ Answer: A

Q39. Which HLD sequence is correct?

A. Database -> API -> User

B. User -> API -> Planner -> LLM -> SQL -> Database -> Result -> Response

C. User -> Kafka -> HTML

D. Redis -> Browser

✅ Answer: B

Q40. Which statement represents an AI Solution Architect?

A. "I know SQL."

B. "I know Python."

C. "I understand how Users, APIs, LLMs, Planners, Memory, Databases, Cache, Queues, and Tools work together to build an intelligent Talk-to-Data Agent."

D. "I know React."

✅ Answer: C
"""

import re

# Format answers
formatted = re.sub(r'✅\s*Answer:\s*([A-D])', r'**Answer:** \1', raw_text, flags=re.IGNORECASE)

md_path = r'E:\Gen AI Online Batch Morning tue-sat\AI_Course\public\docs\hld_revision_problem_prerequisites.md'

frontmatter = '''---
title: "Talk to Data Agent HLD"
topic: "HLD"
date: "2026-07-02"
timing: "9:00 AM - 10:00 AM IST"
description: "Comprehensive HLD review session before solving complex system design challenges."
---

# Talk to Data Agent HLD
Class Timing: 9:00 AM - 10:00 AM IST

Welcome to the daily assessment for **Day 12 - Talk to Data Agent HLD**.
Please attempt all questions below. Explanations will unlock after submission.

'''

with open(md_path, 'w', encoding='utf-8') as out:
    out.write(frontmatter + '\n' + formatted)
print('Successfully wrote 40 questions for Day 12.')
